name: blackjack_final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  playing_cards: ^0.4.1+11
  audioplayers: ^5.2.1
  flutter_xlider: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/player_data.json
    - assets/gambling.jpg
    - assets/audio/jazz-lounge.mp3
    - assets/audio/cash-register-purchase.mp3
    - assets/audio/the-simpsons-nelsons-haha.mp3
    - assets/audio/flip-card.mp3
    - assets/audio/downer-noise.mp3
    - assets/audio/brass-fail.mp3
    - assets/audio/fanfare.mp3
